add variants of SeatCountBadge + minor layout adjustments
eventjet/seatmaps pull request #19
Opened 2023-12-15 14:00 UTC by codingCookie

- `SeatCountBadge`
  - add variant to place on a circle
  - add variant to place on an ellipse - with calculation of badge positioning
- `stories`: 
  - add stories for `SeatCountBadge`-variants

2023-12-20 09:45 UTC, rieschl approved these changes
The design is ok 👍

2023-12-20 10:31 UTC, MidnightDesign requested changes

2023-12-20 10:31 UTC, MidnightDesign commented on packages/seatmaps/src/SeatCountBadge.tsx
> -    containerWidth: number;
That's a BC break.

2023-12-20 10:31 UTC, MidnightDesign commented on packages/seatmaps/src/SeatCountBadge.tsx
> +const badgePositionAdjustment = (containerWidth: number, isCircle = false) => {
Please don't use flag arguments.

2023-12-20 10:31 UTC, MidnightDesign commented on packages/seatmaps/src/SeatCountBadge.tsx
> +export const SeatCountBadgeOnCircle = ({ containerProps, count = 0, color = 'inherit' }: SeatCountBadgeProps) => {
That's a BC break.

2023-12-20 10:31 UTC, MidnightDesign commented on packages/seatmaps/src/SeatCountBadge.tsx
> +export const SeatCountBadgeOnEllipse = ({ containerProps, count = 0, color = 'inherit' }: SeatCountBadgeProps) => {
That's a BC break.

2023-12-20 10:31 UTC, MidnightDesign commented on packages/seatmaps/src/SeatCountBadge.tsx
> +const badgePositionAdjustment = (containerWidth: number, isCircle = false) => {
Also, please don't use nouns as function names.

2023-12-20 14:13 UTC, MidnightDesign approved these changes

2023-12-21 14:45 UTC, MidnightDesign approved these changes

2023-12-22 14:27 UTC, merged